name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in
version: 4.1.0

flutter:
  plugin:
    platform:
      android:
        package: io.flutter.plugins.googlesignin
        pluginClass: GoogleSignInPlugin
      ios:
        pluginClass: FLTGoogleSignInPlugin
      web:
        default_package: google_sign_in_web

dependencies:
  google_sign_in_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  meta: ^1.0.4
  google_sign_in_web: any

dev_dependencies:
  http: ^0.12.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"
