name: video_player_platform_interface
description: A common platform interface for the video_player plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 3.0.0-nullsafety

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.10.0-nullsafety.1

# Don't publish this package until null safety is stable or the package is in the allow list.
publish_to: none

environment:
  sdk: ">=2.10.0-56.0.dev <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
