name: device_info_platform_interface
description: A common platform interface for the device_info plugin.
homepage: https://github.com/flutter/plugins/tree/master/packages/device_info
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.0.0-nullsafety

# Don't publish this package until null safety is stable or the package is in the allow list.
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.3
  plugin_platform_interface:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: packages/plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.10.0-nullsafety.1
  pedantic: ^1.10.0-nullsafety.1

environment:
  sdk: '>=2.10.0-56.0.dev <3.0.0'
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
