name: url_launcher
description: Flutter plugin for launching a URL on Android and iOS. Supports
  web, phone, SMS, and email schemes.
homepage: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
version: 6.0.0-nullsafety

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.urllauncher
        pluginClass: UrlLauncherPlugin
      ios:
        pluginClass: FLTURLLauncherPlugin
      # TODO(mvanbeusekom): Temporary disabled until web is migrated to nnbd (advised by @blasten).
      #web:
      #  default_package: url_launcher_web
      linux:
        default_package: url_laucher_linux
      macos:
        default_package: url_laucher_macos
      windows:
        default_package: url_laucher_windows

dependencies:
  flutter:
    sdk: flutter
  # TODO(mvanbeusekom): Update to use pub.dev once null safety version is published.
  url_launcher_platform_interface:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: packages/url_launcher/url_launcher_platform_interface
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  url_launcher_linux:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: packages/url_launcher/url_launcher_linux
  url_launcher_macos:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: packages/url_launcher/url_launcher_macos
  url_launcher_windows:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: packages/url_launcher/url_launcher_windows
  # TODO(mvanbeusekom): Temporary disabled until web is migrated to nnbd (advised by @blasten).
  #url_launcher_web: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.10.0-nullsafety.1
  mockito: ^4.1.1
  # TODO (mvanbeusekom): Update to use pub.dev once 1.10.0-nullsafety released.
  plugin_platform_interface:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: packages/plugin_platform_interface
  pedantic: ^1.10.0-nullsafety.1

environment:
  sdk: ">=2.10.0-56.0.dev <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
