name: url_launcher_example
description: Demonstrates how to use the url_launcher plugin.

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
    path: ../

dev_dependencies:
  integration_test:
    path: ../../../integration_test
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.1
  mockito: ^4.1.1
  # TODO (mvanbeusekom): Update to use pub.dev once 1.10.0-nullsafety released.
  plugin_platform_interface:
    git:
      url: https://github.com/flutter/plugins.git
      ref: nnbd
      path: packages/plugin_platform_interface

flutter:
  uses-material-design: true
